### ISSUE TITLE
Modern setup configuration

### ISSUE THREAD

**Issue by videlec** [fredstro/hilbertmodgroup#2]
Python packaging is shifting toward havin a `pyproject.toml` at the root of the package that specifies the tool to install the package (for this package this would be `setuptools`). Also it becomes more common to specify the setup options in a `setup.cfg` file rather than in the `setup.py`. This way of doing is much more complete to specify build dependencies and runtime dependencies.

Part of openjournals/joss-reviews#3996

**Comment by fredstro** [comment]
I have removed everything I can from the setup.py and put into the pyproject.toml and setup.cfg.
As far as I can tell the Cython extension modules still need to be in setup.py

**Comment by fredstro** [comment]
This is done.
