### ISSUE TITLE
github workflows to run tests

### ISSUE THREAD

**Issue by videlec** [fredstro/hilbertmodgroup#4]
[github actions](https://docs.github.com/en/actions) provide a way to run tests using the github infrastructure. This is very convenient while working on the code.

Part of openjournals/joss-reviews#3996.

**Comment by fredstro** [comment]
I have added a github action workflow to run tox in a docker container with a number of tests (basically taken from the sage's tox configuration):
- doctests
- coverage
- pycodestyle 
- relint
- codespell

**Comment by videlec** [comment]
Very nice.
