### ISSUE TITLE
TestSuite

### ISSUE THREAD

**Issue by videlec** [fredstro/hilbertmodgroup#8]
sage has some automated tests to check that categories, inheritance, etc are correctly implemented. You can run it via
```
sage: from hilbert_modgroup.upper_half_plane import ComplexPlaneProduct
sage: TestSuite(ComplexPlaneProduct(2)).run()
```
The above fails because
- category is not initialized
- pickling fails

Part of https://github.com/openjournals/joss-reviews/issues/3996

**Comment by fredstro** [comment]
I have fixed pickling (and coercion) and added a TestSuite().run() to all classes.

**Comment by videlec** [comment]
Great!

**Comment by fredstro** [comment]
I think this is fine now.
